name: Run Tests and Push to Testing1 Branch

on:
  push:
    branches:
      - testing

jobs:
  test:
    name: Run Server Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Push changes to testing1 branch
      uses: ad-m/github-push-action@master
      with:
        branch: testing1
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
