name: CI / CD development

on:
  push:
    branches:
    - development
      

jobs:
  test:
    name: Run Server Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Remove .github/workflows directory
      run: rm -rf .github

    - name: List files in directory
      run: ls -a

    - name: Push changes to staging
      uses: ad-m/github-push-action@master
      with:
        branch: staging
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
   
