name: CI / CD development

on:
  push:
    paths-ignore: 
      - .github/workflows/main.yml
    branches:
      - development

jobs:
  test:
    name: Run Server Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
      
      - name: Remove .github/workflows directory
        run: rm -rf .github

      - name: Stash changes
        run: |
          git config --global user.email "djekram33@gmail.com"
          git config --global user.name "Ekram karim"
          git stash

      - name: Pull changes from staging and rebase
        run: |
          git pull origin staging --rebase || true

      - name: Push changes to staging (force push)
        run: git push origin HEAD:staging --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply stashed changes
        run: |
          git stash apply || true
          git add . # Add any changes resulting from stash apply
          git commit -m "Resolve conflicts"
