name: Eco_sample3_test

on:
  push:
    branches:
      - testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.1'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
