# Project Configuration
project:
  name: Waste Management System
  description: A system for managing waste records and customer data.

# Dependencies
dependencies:
  node:
    version: 14.17.0
  npm:
    version: 6.14.13
  packages:
    express: "^4.17.1"
    body-parser: "^1.19.0"
    cookie-parser: "^1.4.5"
    mongodb: "^4.3.0"
    crypto: "^1.0.1"
    express-handlebars: "^5.3.2"

# File Structure
file_structure:
  root:
    - presentation.js
    - business.js
    - persistence.js
    - templates:
        - homepage.handlebars
        - login.handlebars
        - searchRecord.handlebars
        - customerData.handlebars
        - error404.handlebars
    - static:
        - css:
            - styles.css
        - images:
            - logo.png

# Scripts
scripts:
  start: node presentation.js

# Development Environment
dev_environment:
  editor: Visual Studio Code
  git_repo: https://github.com/yourusername/waste-management-system.git
