name: CI / CD development

on:
  push:
    branches:
    - development
      

jobs:
  test:
    name: Run Server Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test
    
    - name: Push changes to staging 
      run: rm -rf .github/workflows

    - name: Remove .github/workflows directory
      run: rm -rf .github/workflows

    - name: Push changes to staging
      run: |
          git add .
          git commit -m "Exclude .github/workflows directory"
          git push origin development:staging --force
