name: CI / CD Testing

on:
  push:
    paths-ignore: 
      - .github/workflows/testing.yml
    branches:
       - testing
  pull_request:
    branches:
       - testing

jobs:
  test:
    name: Run Server Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Remove .github/workflows directory
      run: |
        rm -rf .github/workflows
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

